-- PostgreSQL production baseline for VocabLearning.
-- Manual baseline only. Do not apply legacy SQL Server EF migrations to PostgreSQL.
-- Apply only to an empty PostgreSQL database. Existing objects must be audited or restored, not patched by this file.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username CITEXT NOT NULL,
    email CITEXT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    google_subject VARCHAR(200) NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'LEARNER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_email_verified BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_username_length CHECK (char_length(username::text) BETWEEN 3 AND 50),
    CONSTRAINT ck_users_email_length CHECK (char_length(email::text) BETWEEN 6 AND 100),
    CONSTRAINT ck_users_password_hash_length CHECK (char_length(password_hash) BETWEEN 1 AND 255),
    CONSTRAINT ck_users_google_subject_length CHECK (google_subject IS NULL OR char_length(google_subject) <= 200),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'LEARNER')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_users_deleted_at CHECK (
        (is_deleted = FALSE AND deleted_at IS NULL)
        OR is_deleted = TRUE
    )
);

CREATE UNIQUE INDEX ux_users_google_subject
    ON users (google_subject)
    WHERE google_subject IS NOT NULL;

CREATE TABLE topic (
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    parent_topic_id BIGINT NULL,
    CONSTRAINT uq_topic_name UNIQUE (name),
    CONSTRAINT ck_topic_name_length CHECK (char_length(name::text) BETWEEN 1 AND 100),
    CONSTRAINT ck_topic_not_self_parent CHECK (parent_topic_id IS NULL OR parent_topic_id <> topic_id),
    CONSTRAINT fk_topic_parent
        FOREIGN KEY (parent_topic_id) REFERENCES topic (topic_id)
        ON DELETE SET NULL
);

CREATE TABLE vocabulary (
    vocab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word CITEXT NOT NULL,
    ipa VARCHAR(100) NULL,
    audio_url VARCHAR(2048) NULL,
    level VARCHAR(10) NOT NULL,
    meaning_vi TEXT NOT NULL,
    topic_id BIGINT NULL,
    CONSTRAINT uq_vocabulary_word UNIQUE (word),
    CONSTRAINT ck_vocabulary_word_length CHECK (char_length(word::text) BETWEEN 1 AND 100),
    CONSTRAINT ck_vocabulary_level CHECK (level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    CONSTRAINT fk_vocabulary_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE SET NULL
);

CREATE INDEX ix_vocabulary_topic_id
    ON vocabulary (topic_id);

CREATE TABLE example (
    example_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    sentence TEXT NOT NULL,
    translation TEXT NOT NULL,
    audio_url VARCHAR(2048) NULL,
    CONSTRAINT ck_example_sentence_not_blank CHECK (btrim(sentence) <> ''),
    CONSTRAINT ck_example_translation_not_blank CHECK (btrim(translation) <> ''),
    CONSTRAINT fk_example_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_example_vocab_id
    ON example (vocab_id);

CREATE TABLE exercise (
    exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    exercise_type VARCHAR(50) NOT NULL,
    match_mode VARCHAR(50) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_exercise_type CHECK (exercise_type IN ('MATCH_MEANING', 'FILLING')),
    CONSTRAINT ck_exercise_match_mode CHECK (
        (exercise_type = 'MATCH_MEANING' AND match_mode IN ('MATCH_IPA', 'MATCH_MEANING'))
        OR (exercise_type = 'FILLING' AND match_mode IS NULL)
    ),
    CONSTRAINT fk_exercise_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_exercise_match_mode
    ON exercise (vocab_id, exercise_type, match_mode)
    WHERE match_mode IS NOT NULL;

CREATE UNIQUE INDEX ux_exercise_null_match_mode
    ON exercise (vocab_id, exercise_type)
    WHERE match_mode IS NULL;

CREATE INDEX ix_exercise_vocab_id
    ON exercise (vocab_id);

CREATE TABLE user_vocabulary (
    user_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    note TEXT NOT NULL DEFAULT '',
    first_learned_date TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT pk_user_vocabulary PRIMARY KEY (user_id, vocab_id),
    CONSTRAINT ck_user_vocabulary_status CHECK (status IN ('NEW', 'LEARNING', 'MASTERED')),
    CONSTRAINT fk_user_vocabulary_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_user_vocabulary_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_user_vocabulary_vocab_id
    ON user_vocabulary (vocab_id);

CREATE TABLE progress (
    user_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    interval_days INTEGER NOT NULL DEFAULT 1,
    repetitions INTEGER NOT NULL DEFAULT 0,
    last_review_date TIMESTAMP WITHOUT TIME ZONE NULL,
    next_review_date TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT pk_progress PRIMARY KEY (user_id, vocab_id),
    CONSTRAINT ck_progress_srs CHECK (
        ease_factor >= 1.3
        AND interval_days >= 0
        AND repetitions >= 0
    ),
    CONSTRAINT fk_progress_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_progress_user_vocabulary
        FOREIGN KEY (user_id, vocab_id) REFERENCES user_vocabulary (user_id, vocab_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_progress_user_id_next_review_date
    ON progress (user_id, next_review_date);

CREATE TABLE exercise_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    session_type VARCHAR(20) NOT NULL,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITHOUT TIME ZONE NULL,
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    score REAL NOT NULL DEFAULT 0,
    CONSTRAINT ck_exercise_session_type CHECK (session_type IN ('PRACTICE', 'REVIEW', 'MINI_TEST')),
    CONSTRAINT ck_exercise_session_counts CHECK (
        total_questions >= 0
        AND correct_count >= 0
        AND correct_count <= total_questions
    ),
    CONSTRAINT ck_exercise_session_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT ck_exercise_session_finished_at CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT fk_exercise_session_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_exercise_session_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE NO ACTION
);

CREATE INDEX ix_exercise_session_user_id_started_at
    ON exercise_session (user_id, started_at DESC);

CREATE INDEX ix_exercise_session_topic_id
    ON exercise_session (topic_id);

CREATE TABLE exercise_result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    quality INTEGER NOT NULL DEFAULT 0,
    answered_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_exercise_result_quality CHECK (quality BETWEEN 0 AND 5),
    CONSTRAINT fk_exercise_result_session
        FOREIGN KEY (session_id) REFERENCES exercise_session (session_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_exercise_result_exercise
        FOREIGN KEY (exercise_id) REFERENCES exercise (exercise_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_exercise_result_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION
);

CREATE INDEX ix_exercise_result_user_id_answered_at
    ON exercise_result (user_id, answered_at DESC);

CREATE INDEX ix_exercise_result_session_id_exercise_id
    ON exercise_result (session_id, exercise_id);

CREATE INDEX ix_exercise_result_exercise_id
    ON exercise_result (exercise_id);

CREATE TABLE learning_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    activity_type VARCHAR(20) NOT NULL,
    words_studied INTEGER NOT NULL DEFAULT 0,
    score REAL NOT NULL DEFAULT 0,
    CONSTRAINT ck_learning_log_activity_type CHECK (activity_type IN ('LEARN', 'REVIEW', 'TEST')),
    CONSTRAINT ck_learning_log_words_studied CHECK (words_studied >= 0),
    CONSTRAINT ck_learning_log_score CHECK (score >= 0 AND score <= 100),
    CONSTRAINT fk_learning_log_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_learning_log_session
        FOREIGN KEY (session_id) REFERENCES exercise_session (session_id)
        ON DELETE NO ACTION
);

CREATE UNIQUE INDEX ux_learning_log_session_id
    ON learning_log (session_id);

CREATE INDEX ix_learning_log_user_id_date
    ON learning_log (user_id, date DESC);

CREATE TABLE meaning (
    meaning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    meaning_en TEXT NOT NULL,
    meaning_vi TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    CONSTRAINT ck_meaning_en_not_blank CHECK (btrim(meaning_en) <> ''),
    CONSTRAINT ck_meaning_vi_not_blank CHECK (btrim(meaning_vi) <> ''),
    CONSTRAINT ck_meaning_type_not_blank CHECK (btrim(type) <> ''),
    CONSTRAINT fk_meaning_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_meaning_vocab_id
    ON meaning (vocab_id);

CREATE TABLE password_reset_token (
    password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP WITHOUT TIME ZONE NULL,
    consumed_by_ip VARCHAR(64) NULL,
    CONSTRAINT ck_password_reset_token_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT ck_password_reset_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT fk_password_reset_token_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION
);

CREATE INDEX ix_password_reset_token_token_hash
    ON password_reset_token (token_hash);

CREATE INDEX ix_password_reset_token_user_id_created_at
    ON password_reset_token (user_id, created_at DESC);

CREATE INDEX ix_password_reset_token_expires_at
    ON password_reset_token (expires_at);

CREATE TABLE email_verification_token (
    email_verification_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP WITHOUT TIME ZONE NULL,
    consumed_by_ip VARCHAR(64) NULL,
    CONSTRAINT ck_email_verification_token_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT ck_email_verification_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT fk_email_verification_token_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_email_verification_token_token_hash
    ON email_verification_token (token_hash);

CREATE INDEX ix_email_verification_token_user_id_created_at
    ON email_verification_token (user_id, created_at DESC);

CREATE INDEX ix_email_verification_token_expires_at
    ON email_verification_token (expires_at);

CREATE TABLE sticky_note (
    sticky_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL DEFAULT '',
    color VARCHAR(32) NOT NULL DEFAULT 'yellow',
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sticky_note_content_length CHECK (char_length(content) <= 1000),
    CONSTRAINT ck_sticky_note_color_length CHECK (char_length(color) BETWEEN 1 AND 32),
    CONSTRAINT ck_sticky_note_updated_at CHECK (updated_at >= created_at),
    CONSTRAINT fk_sticky_note_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_sticky_note_user_id_is_pinned_updated_at
    ON sticky_note (user_id, is_pinned DESC, updated_at DESC);

CREATE TABLE learning_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id BIGINT NULL,
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_index INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    abandoned_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_learning_session_mode CHECK (mode IN ('STUDY', 'REVIEW')),
    CONSTRAINT ck_learning_session_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT ck_learning_session_current_index CHECK (current_index >= 0),
    CONSTRAINT ck_learning_session_updated_at CHECK (updated_at >= started_at),
    CONSTRAINT fk_learning_session_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_learning_session_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE SET NULL
);

CREATE INDEX ix_learning_session_user_id_status
    ON learning_session (user_id, status);

CREATE INDEX ix_learning_session_user_id_status_updated_at
    ON learning_session (user_id, status, updated_at DESC);

CREATE INDEX ix_learning_session_topic_id
    ON learning_session (topic_id);

CREATE TABLE learning_session_item (
    session_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    quality INTEGER NULL,
    is_answered BOOLEAN NOT NULL DEFAULT FALSE,
    answered_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_learning_session_item_order_index CHECK (order_index >= 0),
    CONSTRAINT ck_learning_session_item_quality CHECK (quality IS NULL OR (quality BETWEEN 0 AND 5)),
    CONSTRAINT ck_learning_session_item_answered CHECK (
        (is_answered = FALSE AND answered_at IS NULL AND quality IS NULL)
        OR is_answered = TRUE
    ),
    CONSTRAINT fk_learning_session_item_session
        FOREIGN KEY (session_id) REFERENCES learning_session (session_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_learning_session_item_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_learning_session_item_session_vocab
    ON learning_session_item (session_id, vocab_id);

CREATE INDEX ix_learning_session_item_session_order
    ON learning_session_item (session_id, order_index);

CREATE INDEX ix_learning_session_item_vocab_id
    ON learning_session_item (vocab_id);
