CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    google_subject VARCHAR(200) NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'LEARNER',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_email_verified BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'LEARNER')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_google_subject
    ON users (google_subject)
    WHERE google_subject IS NOT NULL;

CREATE TABLE IF NOT EXISTS topic (
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    parent_topic_id BIGINT NULL
);

CREATE TABLE IF NOT EXISTS vocabulary (
    vocab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NULL,
    ipa TEXT NULL,
    audio_url TEXT NULL,
    level TEXT NULL,
    meaning_vi TEXT NULL,
    topic_id BIGINT NULL,
    CONSTRAINT fk_vocabulary_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS example (
    example_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    sentence TEXT NOT NULL,
    translation TEXT NOT NULL,
    audio_url TEXT NULL,
    CONSTRAINT fk_example_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_vocabulary (
    user_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    status TEXT NOT NULL,
    note TEXT NOT NULL,
    first_learned_date TIMESTAMP NULL,
    CONSTRAINT pk_user_vocabulary PRIMARY KEY (user_id, vocab_id),
    CONSTRAINT fk_user_vocabulary_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT ck_user_vocabulary_status CHECK (status IN ('NEW', 'LEARNING', 'MASTERED'))
);

CREATE TABLE IF NOT EXISTS progress (
    user_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    ease_factor DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    interval_days INTEGER NOT NULL DEFAULT 1,
    repetitions INTEGER NOT NULL DEFAULT 0,
    last_review_date TIMESTAMP NULL,
    next_review_date TIMESTAMP NULL,
    CONSTRAINT pk_progress PRIMARY KEY (user_id, vocab_id),
    CONSTRAINT fk_progress_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_progress_user_vocabulary
        FOREIGN KEY (user_id, vocab_id) REFERENCES user_vocabulary (user_id, vocab_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_progress_user_id_next_review_date
    ON progress (user_id, next_review_date);

CREATE TABLE IF NOT EXISTS exercise (
    exercise_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    exercise_type TEXT NOT NULL,
    match_mode TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_exercise_exercise_type CHECK (exercise_type IN ('MATCH_MEANING', 'FILLING')),
    CONSTRAINT ck_exercise_match_mode CHECK (
        match_mode IS NULL OR match_mode IN ('MATCH_IPA', 'MATCH_MEANING')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_exercise_vocab_id_type_match_mode
    ON exercise (vocab_id, exercise_type, match_mode);

CREATE TABLE IF NOT EXISTS exercise_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    session_type TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP NULL,
    total_questions INTEGER NOT NULL,
    correct_count INTEGER NOT NULL,
    score REAL NOT NULL,
    CONSTRAINT fk_exercise_session_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_exercise_session_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS ix_exercise_session_user_id_started_at
    ON exercise_session (user_id, started_at);

CREATE TABLE IF NOT EXISTS exercise_result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    quality INTEGER NOT NULL,
    answered_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_exercise_result_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_exercise_result_session
        FOREIGN KEY (session_id) REFERENCES exercise_session (session_id)
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS ix_exercise_result_user_id_answered_at
    ON exercise_result (user_id, answered_at);

CREATE INDEX IF NOT EXISTS ix_exercise_result_session_id_exercise_id
    ON exercise_result (session_id, exercise_id);

CREATE TABLE IF NOT EXISTS learning_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    date TIMESTAMP NOT NULL,
    activity_type TEXT NOT NULL,
    words_studied INTEGER NOT NULL,
    score REAL NOT NULL,
    CONSTRAINT fk_learning_log_session
        FOREIGN KEY (session_id) REFERENCES exercise_session (session_id)
        ON DELETE NO ACTION,
    CONSTRAINT ck_learning_log_activity_type CHECK (activity_type IN ('LEARN', 'REVIEW', 'TEST'))
);

CREATE INDEX IF NOT EXISTS ix_learning_log_user_id_date
    ON learning_log (user_id, date);

CREATE UNIQUE INDEX IF NOT EXISTS ix_learning_log_session_id
    ON learning_log (session_id);

CREATE TABLE IF NOT EXISTS meaning (
    meaning_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id BIGINT NOT NULL,
    meaning_en TEXT NOT NULL,
    meaning_vi TEXT NOT NULL,
    type TEXT NOT NULL,
    CONSTRAINT fk_meaning_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP NULL,
    consumed_by_ip VARCHAR(64) NULL,
    CONSTRAINT fk_password_reset_token_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_token_hash
    ON password_reset_token (token_hash);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_user_id_created_at
    ON password_reset_token (user_id, created_at);

CREATE INDEX IF NOT EXISTS ix_password_reset_token_expires_at
    ON password_reset_token (expires_at);

CREATE TABLE IF NOT EXISTS email_verification_token (
    email_verification_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP NULL,
    consumed_by_ip VARCHAR(64) NULL,
    CONSTRAINT fk_email_verification_token_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_email_verification_token_token_hash
    ON email_verification_token (token_hash);

CREATE INDEX IF NOT EXISTS ix_email_verification_token_user_id_created_at
    ON email_verification_token (user_id, created_at);

CREATE INDEX IF NOT EXISTS ix_email_verification_token_expires_at
    ON email_verification_token (expires_at);

CREATE TABLE IF NOT EXISTS sticky_note (
    sticky_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL DEFAULT '',
    color VARCHAR(32) NOT NULL DEFAULT 'yellow',
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sticky_note_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_sticky_note_user_id_is_pinned_updated_at
    ON sticky_note (user_id, is_pinned, updated_at);
