// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VocabLearning.Data;

#nullable disable

namespace VocabLearning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514090434_FixPasswordResetTokenDeleteBehavior")]
    partial class FixPasswordResetTokenDeleteBehavior
    {
    }
}
