// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabLearning.Data;

#nullable disable

namespace VocabLearning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407151950_Refactor_ExerciseSession_SRS")]
    partial class Refactor_ExerciseSession_SRS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VocabLearning.Models.Example", b =>
                {
                    b.Property<long>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("example_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExampleId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audio_url");

                    b.Property<string>("ExampleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentence");

                    b.Property<string>("ExampleVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation");

                    b.Property<long>("VocabId")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    b.HasKey("ExampleId");

                    b.HasIndex("VocabId");

                    b.ToTable("example", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Exercise", b =>
                {
                    b.Property<long>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExerciseId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MatchMode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("match_mode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("exercise_type");

                    b.Property<long>("VocabId")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    b.HasKey("ExerciseId");

                    b.HasIndex("VocabId", "Type", "MatchMode")
                        .IsUnique()
                        .HasFilter("[match_mode] IS NOT NULL");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.ExerciseResult", b =>
                {
                    b.Property<long>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("result_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResultId"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_at");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ResultId");

                    b.HasIndex("SessionId", "ExerciseId");

                    b.HasIndex("UserId", "AnsweredAt");

                    b.ToTable("exercise_result", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.ExerciseSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int")
                        .HasColumnName("correct_count");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("exercise_session", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.LearningLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("WordsStudied")
                        .HasColumnType("int")
                        .HasColumnName("words_studied");

                    b.HasKey("LogId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("learning_log", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Meaning", b =>
                {
                    b.Property<long>("MeaningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("meaning_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MeaningId"));

                    b.Property<string>("MeaningEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meaning_en");

                    b.Property<string>("MeaningVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meaning_vi");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<long>("VocabId")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    b.HasKey("MeaningId");

                    b.HasIndex("VocabId");

                    b.ToTable("meaning", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Progress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VocabId")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    b.Property<float>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(2.5f)
                        .HasColumnName("ease_factor");

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("interval_days");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_review_date");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_review_date");

                    b.Property<int>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("repetitions");

                    b.HasKey("UserId", "VocabId");

                    b.HasIndex("UserId", "NextReviewDate");

                    b.ToTable("progress", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Topic", b =>
                {
                    b.Property<long>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TopicId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentTopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_topic_id");

                    b.HasKey("TopicId");

                    b.ToTable("topic", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.UserVocabulary", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("VocabId")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    b.Property<DateTime?>("FirstLearnedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("first_learned_date");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("UserId", "VocabId");

                    b.ToTable("user_vocabulary", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("google_subject");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasFilter("[google_subject] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Vocabulary", b =>
                {
                    b.Property<long>("VocabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VocabId"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audio_url");

                    b.Property<string>("Ipa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ipa");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<string>("MeaningVi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meaning_vi");

                    b.Property<long?>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("word");

                    b.HasKey("VocabId");

                    b.HasIndex("TopicId");

                    b.ToTable("vocabulary", (string)null);
                });

            modelBuilder.Entity("VocabLearning.Models.Example", b =>
                {
                    b.HasOne("VocabLearning.Models.Vocabulary", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VocabLearning.Models.ExerciseResult", b =>
                {
                    b.HasOne("VocabLearning.Models.ExerciseSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VocabLearning.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabLearning.Models.ExerciseSession", b =>
                {
                    b.HasOne("VocabLearning.Models.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VocabLearning.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabLearning.Models.LearningLog", b =>
                {
                    b.HasOne("VocabLearning.Models.ExerciseSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabLearning.Models.Meaning", b =>
                {
                    b.HasOne("VocabLearning.Models.Vocabulary", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VocabLearning.Models.Progress", b =>
                {
                    b.HasOne("VocabLearning.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VocabLearning.Models.UserVocabulary", null)
                        .WithOne()
                        .HasForeignKey("VocabLearning.Models.Progress", "UserId", "VocabId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabLearning.Models.UserVocabulary", b =>
                {
                    b.HasOne("VocabLearning.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VocabLearning.Models.Vocabulary", b =>
                {
                    b.HasOne("VocabLearning.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("VocabLearning.Models.Vocabulary", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
