-- Admin Phase 2: auditable XP adjustments and leaderboard visibility.

BEGIN;

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS is_hidden_from_leaderboard BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.xp_adjustment (
    adjustment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE NO ACTION,
    amount INTEGER NOT NULL,
    reason TEXT NOT NULL,
    created_by_admin_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE NO ACTION,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_xp_adjustment_amount CHECK (amount <> 0),
    CONSTRAINT ck_xp_adjustment_reason CHECK (btrim(reason) <> '')
);

CREATE INDEX IF NOT EXISTS ix_xp_adjustment_user_id_created_at
    ON public.xp_adjustment (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE NO ACTION,
    target_user_id BIGINT NULL REFERENCES public.users(user_id) ON DELETE NO ACTION,
    action VARCHAR(80) NOT NULL,
    reason TEXT NULL,
    metadata_json TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_admin_audit_log_action CHECK (btrim(action) <> '')
);

CREATE INDEX IF NOT EXISTS ix_admin_audit_log_admin_user_id_created_at
    ON public.admin_audit_log (admin_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_admin_audit_log_target_user_id_created_at
    ON public.admin_audit_log (target_user_id, created_at DESC);

COMMIT;
