-- Migration: add learning_session + learning_session_item tables.
-- Date: 2026-05-16
-- Target: existing PostgreSQL databases (dev/prod) that already ran init.sql before
--         Step 1 of the LearningSession refactor. Schema mirrors database/postgres/init.sql.
-- Idempotent: safe to re-run. Uses CREATE TABLE / INDEX IF NOT EXISTS.
-- Constraints live inside CREATE TABLE because PostgreSQL has no
-- ADD CONSTRAINT IF NOT EXISTS; re-running on an existing table is a no-op
-- and will NOT attempt to add duplicate constraints.

BEGIN;

CREATE TABLE IF NOT EXISTS learning_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id BIGINT NULL,
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_index INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE NULL,
    abandoned_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_learning_session_mode CHECK (mode IN ('STUDY', 'REVIEW')),
    CONSTRAINT ck_learning_session_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT ck_learning_session_current_index CHECK (current_index >= 0),
    CONSTRAINT ck_learning_session_updated_at CHECK (updated_at >= started_at),
    CONSTRAINT fk_learning_session_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE NO ACTION,
    CONSTRAINT fk_learning_session_topic
        FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_learning_session_user_id_status
    ON learning_session (user_id, status);

CREATE INDEX IF NOT EXISTS ix_learning_session_user_id_status_updated_at
    ON learning_session (user_id, status, updated_at DESC);

CREATE INDEX IF NOT EXISTS ix_learning_session_topic_id
    ON learning_session (topic_id);

CREATE TABLE IF NOT EXISTS learning_session_item (
    session_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    vocab_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    quality INTEGER NULL,
    is_answered BOOLEAN NOT NULL DEFAULT FALSE,
    answered_at TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT ck_learning_session_item_order_index CHECK (order_index >= 0),
    CONSTRAINT ck_learning_session_item_quality CHECK (quality IS NULL OR (quality BETWEEN 0 AND 5)),
    CONSTRAINT ck_learning_session_item_answered CHECK (
        (is_answered = FALSE AND answered_at IS NULL AND quality IS NULL)
        OR is_answered = TRUE
    ),
    CONSTRAINT fk_learning_session_item_session
        FOREIGN KEY (session_id) REFERENCES learning_session (session_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_learning_session_item_vocabulary
        FOREIGN KEY (vocab_id) REFERENCES vocabulary (vocab_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_learning_session_item_session_vocab
    ON learning_session_item (session_id, vocab_id);

CREATE INDEX IF NOT EXISTS ix_learning_session_item_session_order
    ON learning_session_item (session_id, order_index);

CREATE INDEX IF NOT EXISTS ix_learning_session_item_vocab_id
    ON learning_session_item (vocab_id);

COMMIT;
