-- Migration: add DataProtectionKeys table for ASP.NET Core key persistence.
-- Date: 2026-05-23
-- Target: existing PostgreSQL databases (dev/prod/Neon) created from init.sql
--         before DataProtection keys were persisted to the database.
-- Idempotent: safe to re-run (CREATE TABLE IF NOT EXISTS).
--
-- Rationale: Render containers have ephemeral filesystems. Default DataProtection
-- stores keys under ~/.aspnet/DataProtection-Keys, which is lost on restart/redeploy,
-- invalidating auth cookies and antiforgery tokens. PersistKeysToDbContext<AppDbContext>
-- stores the key ring here instead. Table/column names use EF defaults (quoted
-- PascalCase) and must match exactly.

BEGIN;

CREATE TABLE IF NOT EXISTS "DataProtectionKeys" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FriendlyName" TEXT NULL,
    "Xml" TEXT NULL
);

COMMIT;
